# Generated by Django 3.0.8 on 2020-10-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=100)),
                ('plat', models.CharField(default='', max_length=10)),
                ('gambar', models.ImageField(upload_to='img/mobil/')),
                ('gambar2', models.ImageField(upload_to='img/mobil/')),
                ('gambar3', models.ImageField(upload_to='img/mobil/')),
                ('gambar4', models.ImageField(blank=True, upload_to='img/mobil/')),
                ('ditambahkan', models.DateTimeField(auto_now_add=True)),
                ('tipe', models.CharField(choices=[('Covertible', 'Covertible'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('MPV', 'MPV')], default='MPV', max_length=20)),
                ('harga', models.IntegerField(default=100000)),
                ('deskripsi', models.TextField()),
                ('transmisi', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Manual', max_length=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'ordering': ['harga'],
            },
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, null=True)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_mobil.Mobil')),
                ('nama', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=100)),
                ('KTP', models.ImageField(upload_to='img/ktp')),
                ('KK', models.ImageField(upload_to='img/kk')),
                ('harga', models.IntegerField(blank=True, editable=False, null=True)),
                ('pesanan_dibuat', models.DateTimeField(auto_now_add=True, null=True)),
                ('tgl_pesan', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('denda', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('selesai', models.BooleanField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_mobil.Mobil')),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
