# Generated by Django 3.1.2 on 2020-10-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimoni',
            options={'ordering': ['-dibuat_pada']},
        ),
    ]
