# Generated by Django 3.0.8 on 2020-10-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sewa_mobil', '0002_auto_20201013_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=100)),
                ('KTP', models.ImageField(upload_to='img/ktp')),
                ('KK', models.ImageField(upload_to='img/kk')),
                ('harga', models.IntegerField(blank=True)),
                ('lama', models.IntegerField()),
                ('tgl_pesan', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('denda', models.IntegerField(blank=True, null=True)),
                ('selesai', models.BooleanField(blank=True, default=False)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('mobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sewa_mobil.Mobil')),
                ('user', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Persyaratan',
        ),
    ]
