# Generated by Django 3.0.8 on 2020-10-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0003_auto_20201014_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
