# Generated by Django 3.0.8 on 2020-10-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0004_pesanan_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='gambar4',
            field=models.ImageField(blank=True, upload_to='img/mobil/'),
        ),
    ]
