# Generated by Django 3.0.8 on 2020-10-15 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0007_remove_pesanan_lama'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobil',
            name='ditambahkan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
