# Generated by Django 3.1.2 on 2020-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0008_mobil_ditambahkan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='harga',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
