# Generated by Django 3.1.2 on 2020-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa_mobil', '0010_auto_20201017_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='selesai',
            field=models.CharField(default='Menunggu Konfirmasi', max_length=100),
        ),
    ]
